[package]
name = "spheres"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
[dependencies.uuid]
version = "1.19.0"
features = [
    "v4",

]

